version: "3"

services:
  frontend:
    image: samyampradhan/weather-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - weather-app-network

  backend:
    image: samyampradhan/weather-backend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - weather-app-network

networks:
  weather-app-network:
    driver: bridge
