version: "3.9"

services:
  backend:
    build: ./backend
    image: weather-backend
    container_name: weatherapp-backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - weather-network

  frontend:
    build: ./frontend
    platform: linux/arm64
    image: weather-frontend
    container_name: weatherapp-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge